server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  # 配置逻辑删除
#  global-config:
#    db-config:
#      logic-delete-field: status  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
cz:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位 秒
    expire: 604800
    header: Authorization
